### ISSUE TITLE
Gpiote.h, out, in config er 4

### ISSUE THREAD

**Issue by erlwit** [ITK-TTK4235/lab_3#4]
I gpiote.h så er out, in og config registrene 4 lang, men de skal bruke 5, 1 button og 4 leds. Det er bare å trekke en fra hver reserved under de respektive registrene, men tror dette skaper unødvendig forvirring. Det er også 4 på ppi men der gir det mening tror jeg.

**Comment by erlwit** [comment]
Fra:
typedef struct {
	// Tasks
	volatile uint32_t OUT[4];
	// Events
	volatile uint32_t RESERVED0[60];
	volatile uint32_t IN[4];
	volatile uint32_t RESERVED1[27];
	volatile uint32_t PORT;
	// Registers
	volatile uint32_t RESERVED2[96];
	volatile uint32_t INTEN;
	volatile uint32_t INTENSET;
	volatile uint32_t INTENCLR;
	volatile uint32_t RESERVED3[129];
	volatile uint32_t CONFIG[4];
} NRF_GPIOTE_REG;

Til:
typedef struct {
	// Tasks
	volatile uint32_t OUT[5];
	// Events
	volatile uint32_t RESERVED0[59];
	volatile uint32_t IN[5];
	volatile uint32_t RESERVED1[26];
	volatile uint32_t PORT;
	// Registers
	volatile uint32_t RESERVED2[96];
	volatile uint32_t INTEN;
	volatile uint32_t INTENSET;
	volatile uint32_t INTENCLR;
	volatile uint32_t RESERVED3[129];
	volatile uint32_t CONFIG[5];
} NRF_GPIOTE_REG;

**Comment by erlwit** [comment]
Fikk testet of det funker med bare 4 også, men da går den vel out of index så litt skummelt kanskje.

**Comment by terjejacobsson** [comment]
Ser i databladet at det minneområdet faktisk skal være 8 stort! Bra sett!
