### ISSUE TITLE
gpite og ppi

### ISSUE THREAD

**Issue by erlwit** [ITK-TTK4235/lab_3#5]
I 3.2 i main dokumentet står det at buttons og leds ikke må slås på eksplisitt med button_init() f.eks. Men en av gruppene fikk det ikke til å funke uten button init så lurer på om dette er mer missvisende enn nytting, selv om det kanksje er en måte det skjer automatisk på.

**Comment by tordnat** [comment]
Pull-up skjer ikke automatisk. Mulig det er svaret

**Comment by tordnat** [comment]
@erlwit kan du prøve å kun sette pull-up og se om det funker?

**Comment by erlwit** [comment]
Har ikke mulighet nå dessverre men det var ikke nødvendig med led_init, men funket ikke uten button_init selv om ppi.c og gpiote.c var like som fasiten. (Bortsett fra at i lf står d 0<<13 som sikkert henger igjen fra gammelt av og skal være 0<<20 for å sette ledsene av som av for initial condition)

**Comment by tordnat** [comment]
LF oppdatert, oppgavetekst oppdatert
